### ISSUE TITLE
Doesn't open links in "Build a real game" chapter

### ISSUE THREAD

**Issue by dfyz8-g** [soywiz-archive/docs-old.korge.org#103]
Hello!
I'd like to use Korge. I've opened docs to see how to use it.
I can't open any links in "Build a real game" chapter for 2048 game example.
I can find it i tutorials section in site but in docs it doesn't work.
Furthermore, In the start of 2048 game tutorials, I see link to previous part, it also doesn't work.
Please fix it.
Also, I have question: Is still actual tutorial (2048 game) for Korge 3.0?
Thanks

**Comment by soywiz** [comment]
Thanks for reporting. Fixed
