### ISSUE TITLE
Provide info how one may switch between compiling for Android/iOS/JVM/JS

### ISSUE THREAD

**Issue by matkoniecz** [soywiz-archive/docs-old.korge.org#12]
It will probably end in now empty https://korlibs.soywiz.com/korge/tutorials/

**Comment by RezMike** [comment]
@matkoniecz, @soywiz is it already implemented here: https://korlibs.soywiz.com/korge/targets/?

**Comment by matkoniecz** [comment]
Still has no info how can I make APK file for debugging run. It mentions just AAR package files to upload the store.

**Comment by RezMike** [comment]
@soywiz
