### ISSUE TITLE
Missing GRADLE_METADATA documentation

### ISSUE THREAD

**Issue by penn5** [soywiz-archive/docs-old.korge.org#16]
Most of the libraries are multiplatform and hence require `enableFeaturePreview("GRADLE_METADATA")` lines in settings.gradle(.kts). Personally, I was unable to get Krypto working on a Kotlin/Native (not multiplatform) project without that line (spent the whole day searching) and I think it would be a good thing to mention in the docs.

**Comment by soywiz** [comment]
I believe this is not an issue anymore. Since metadata is already the default. Closing this
