### ISSUE TITLE
Blog in navigation points to 404

### ISSUE THREAD

**Issue by TobseF** [soywiz-archive/docs-old.korge.org#17]
The **Blog** link in the top navigation points to 
https://soywiz.com/tag/korlibs/
which results on a **404** page.

The current hosted site seems to be outdated. In the code the link looks fine:
https://github.com/korlibs/korlibs.soywiz.com/blob/f2afc23b7252e958b872fee39f21bef69ad859a1/_layouts/default.html

**Comment by RezMike** [comment]
@TobseF I think it's fixed now.
