### ISSUE TITLE
Wrong navigation on the main page

### ISSUE THREAD

**Issue by RezMike** [soywiz-archive/docs-old.korge.org#2]
When you click on any block of the korlibs structure on the main page, its content opens in the same container, not in a new page.

![51935839104](https://user-images.githubusercontent.com/19624167/56801623-1887d580-6848-11e9-9d4c-18e952c9a14a.png)
![51935839104](https://user-images.githubusercontent.com/19624167/56801786-95b34a80-6848-11e9-8e0e-56b02d0ac977.png)

**Comment by soywiz** [comment]
This seems that I updated the svg without https://github.com/korlibs/korlibs.soywiz.com/blob/master/fix_svg_target.kt

**Comment by RezMike** [comment]
Fixed in #10, can be closed
