### ISSUE TITLE
Orientation parameter in build.gradle does not affect Android target

### ISSUE THREAD

**Issue by arnis71** [soywiz-archive/docs-old.korge.org#32]
Specifying Orientation.LANDSCAPE does not force the android app to go to the Landscape mode by default because the generated manifest does not have such property. 

How can I modify the generated android project? I would like to know more about how this library works so can someone show me the direction where to dig to find how to modify generate android project? I can even make a PR for this and maybe some more Android specific stuff in the future.

**Comment by soywiz** [comment]
Manifest is generated here:
https://github.com/korlibs/korge-plugins/blob/22c567954d612bbc787b32629a1ba51dc13a72da/korge-gradle-plugin/src/main/kotlin/com/soywiz/korge/gradle/targets/android/Android.kt#L275

The `korge` variable holds the extension that includes orientation.
PRs are welcome. Thanks!

**Comment by arnis71** [comment]
Thank you! I will take look and hopefully make it work.

**Comment by arnis71** [comment]
@soywiz I made a fix for orientation but while I am at it I think it is also important to add parameters for sdk versions namely `compileSdkVersion`, `minSdkVersion` and `targetSdkVersion`. What do you think about it?

Also in order to do true fullscreen (right now the navbar is still visible) on Android you must call `setSystemUiVisibility` in the activity and set the flags. Can I propose a fix for this in `KorgwActivity`?

**Comment by soywiz** [comment]
Sure. You can propose anything that is missing👍

**Comment by arnis71** [comment]
I have created a pull request for this so I am closing this issue.
