### ISSUE TITLE
docs: incorrect syntax highlighting

### ISSUE THREAD

**Issue by soywiz** [soywiz-archive/docs-old.korge.org#7]
From @MairwunNx 

As you can see, on the screenshot, incorrect syntax highlighting, red and bright red on a dark background looks very bad, other colors are good, it would not be bad if the color was replaced with a calmer :), if you need help choosing colors, I will try to help 😉

https://github.com/korlibs/korge/issues/34

**Comment by RezMike** [comment]
Fixed in #10, can be closed
