### ISSUE TITLE
Update documentation about the visual editor

### ISSUE THREAD

**Issue by soywiz** [soywiz-archive/docs-old.korge.org#88]

**Comment by kaimatzu** [comment]
Frustrated that I can't use the visual editor at all because ktree is going to be deprecated :(

**Comment by soywiz** [comment]
@kaimatzu it is deprecated, but when removed it will be replaced with something else, and will provide a way to migrate.
Also in the worst case it gets deprecated and no migration tool is provided, you can still [copy this file to your project](https://github.com/korlibs/korge-next/blob/12ef256565ff475d7d391eb38d68162999e2761a/korge/src/commonMain/kotlin/com/soywiz/korge/view/ktree/KTree.kt) and continue having ktree support. So no worries at all:
